fetchWeather function Completed
RajeevKumarSinha/os-traning-tasks pull request #1
Opened 2023-08-20 19:31 UTC by RajeevKumarSinha

I have taken an array of cities and after fetching all possible cities weather console logging the temperature and wind speed of the city and if there is any error in fetching the data then logging the error.

2023-08-21 04:16 UTC, rohandhamapurkar requested changes

2023-08-21 04:16 UTC, rohandhamapurkar commented on js-problems/13-weather-api/fetchWeatherData.js
> +    const cityWeather = await getJson(
here you are awaiting the response for each city and then proceeding forward is there any way to make this faster?

2023-08-21 20:25 UTC, RajeevKumarSinha commented on js-problems/13-weather-api/fetchWeatherData.js
> +  //   const cityWeather = await getJson(
![Screenshot (36)](https://github.com/RajeevKumarSinha/os-traning-tasks/assets/77339429/51dc69d1-a0ce-4e3c-8c7d-aa967cfcca6c)

2023-08-21 20:27 UTC, RajeevKumarSinha commented on js-problems/13-weather-api/fetchWeatherData.js
> +  //   const cityWeather = await getJson(
This is the  previous code which makes  api calls sequentially or one at a time.

2023-08-21 20:30 UTC, RajeevKumarSinha commented on js-problems/13-weather-api/fetchWeatherData.js
> +
![Screenshot (37)](https://github.com/RajeevKumarSinha/os-traning-tasks/assets/77339429/a2b7cb47-73db-4df9-ac99-3d25f0dd4cf3)

2023-08-21 20:42 UTC, RajeevKumarSinha commented on js-problems/13-weather-api/fetchWeatherData.js
> +
New code, on line no. 63 added  urlCities array to store the getJson function as callback for every city,  then on line 69 packed citiesWeather array using rest operator to store objects as response from the calling of Promise.all for urlCities array, here Promise.all executes all the callbacks present in urlCities in parallel.

2023-08-21 20:45 UTC, RajeevKumarSinha reviewed
I have made the changes in the code for making it faster.

2023-08-22 09:03 UTC, rohandhamapurkar commented on js-problems/13-weather-api/fetchWeatherData.js
> +  const [...citiesWeather] = await Promise.all(urlCities);
Explore just writing `citiesWeather`

2023-08-28 07:52 UTC, merged